### ISSUE TITLE
lazy-load libraries in browser iframe runner

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#154]
Currently we load build all browser libraries (and their dependencies) into one big js file with `component build`. This is unsustainable as the number of libs grows. It would make development easier if we could lazy-load these libs as they are added to the graph in the UI.

I was doing this with [yepnope](http://yepnopejs.com/) in Meemoo, and it worked.

When module added to graph:

```
unless Meemoo.modules[name]
  yepnope "modules/#{name}.js"
```

In component:

```
unless Window.Library
  yepnope "path/to/lib.js"
```

Is there a way that we could do something like this? Would require some `require` hacking, and building libs as separately-loadable js files, and changes to how we're doing the component library. But it seems possible. This looks similar: http://www.joezimjs.com/javascript/lazy-loading-javascript-with-requirejs/

Building a project's graphs and deps into one file could then be part of the deploy step.

**Comment by jonnor** [comment]
We no longer bundle the iframe runtime in noflo-ui. Instead we are using `grunt-noflo-browser` to build the same thing in https://github.com/noflo/noflo-browser. One can build a similar thing, have it locally or deploy pulically, and then add these as runtimes by URL. This reduces the issue here quite a bit.

**Comment by bergie** [comment]
Moved to https://github.com/noflo/noflo-browser/issues/3
