### ISSUE TITLE
github import: (subgraph name) not available with base...

### ISSUE THREAD

**Issue by forresto** [noflo/noflo-ui#375]
1. import this project [forresto/noflo-feature-demo](https://github.com/forresto/noflo-feature-demo)
2. open it
3. many notificaitons:

> Uncaught Error: Component noflo-feature-demo/feature_demo not available with base noflo-ui-preview

Also, the main graph setting isn't used.

Both issues could be because I first created the project a couple months ago, and pushed for the first time today. When I have more time I'll try to duplicate with a new project.

**Comment by bergie** [comment]
It seems to sync fine to Flowhub with <https://app.flowhub.io/#github/forresto/noflo-feature-demo>

![screenshot 2018-01-08 at 18 30 14](https://user-images.githubusercontent.com/3346/34683339-12a9578a-f4a2-11e7-9a1d-d46336a055da.png)

![screenshot 2018-01-08 at 18 31 42](https://user-images.githubusercontent.com/3346/34683388-30e03020-f4a2-11e7-8076-9fbfda15018b.png)

However, it is not startable since the noflo-browser runtime doesn't include noflo-ccv:

> Error: Component ccv/FindFaces not available with base browser

Note: the easiest way to ensure correct main graph is used is to name that graph `main.json`.

Closing here since the "not startable" issue is on the runtime side, not in Flowhub.
