### ISSUE TITLE
Login fails in Chrome app

### ISSUE THREAD

**Issue by jonnor** [noflo/noflo-ui#657]
In `git master`. When pressing `Login` in the Chrome app, then I get passed to Github for auth, but upon completing I'm redirected to what seems to be `localhost:9999/` instead of whatever the Chrome app url thing should be.

**Comment by bergie** [comment]
With 0.15.0 we at least provide a clearer error message:

![screenshot 2017-02-16 at 15 44 56](https://cloud.githubusercontent.com/assets/3346/23025644/f25c2cd0-f45e-11e6-9225-86ad4fc30bcd.png)

What we need to do is to configure a separate GitHub OAuth app for the Chrome app to use, since it has a different callback URL.
