### ISSUE TITLE
question about components

### ISSUE THREAD

**Issue by ferrec** [noflo/noflo-ui#692]
Hello,
Is there a way to add dynamically an entry (inout port) for a component ? 
thanks for the answer.

**Comment by bergie** [comment]
Based on the IRC discussion, you're using NoFlo. In NoFlo you can add ports dynamically using the `inPorts` and `outPorts` method `add`. However, a problem is that then you will also have to connect the edges dynamically, as NoFlo will not allow edges connected to non-existing ports.

An easier option is to use an addressable port (https://github.com/noflo/noflo/issues/90) and assign the meaning to the different port indexes instead of different ports.

We use addressable ports quite a bit for dynamic routing. For example, the GroupRouter allows you to specify routing rules as an IIP and then connect to different outport indexes

https://github.com/noflo/noflo-routers/blob/master/spec/GroupRouter.coffee#L298

Example from noflo-ui itself:
https://github.com/noflo/noflo-ui/blob/master/graphs/GithubSynchronization.fbp#L7
